version: '3.8'

services:
  email-catcher:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: email-catcher
    environment:
      - .env
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
      - ./data:/app/data
    command: python src/main.py
    stdin_open: true
    tty: true
